// GENERATED FILE — do not hand-edit under normal circumstances. Regenerate
// with `pnpm --filter @ori/db db:generate-types` (requires the local
// Supabase stack running via `pnpm supabase start`) after any migration
// that changes the `public` schema.
//
// NOTE: this specific revision was hand-reconstructed against the remote
// project (Docker/Podman — required by `supabase gen types --db-url` — was
// unavailable in this environment) rather than generated by the CLI. The
// shape is verified against packages/db/migrations/*.sql and a live
// `information_schema.columns` query against the migrated remote database
// (see the reference-data-module SCHEMA_DECISIONS.md entry), which is the
// actual source of truth. Prefer regenerating for real via `--local` or
// `--project-id` the next time either is available, rather than
// hand-editing further.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never;
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      graphql: {
        Args: {
          extensions?: Json;
          operationName?: string;
          query?: string;
          variables?: Json;
        };
        Returns: Json;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
  public: {
    Tables: {
      companies: {
        Row: {
          id: string;
          name: string;
          type: Database["public"]["Enums"]["company_type"];
          status: Database["public"]["Enums"]["company_status"];
          default_pickup_time: string | null;
          transporter_company_id: string | null;
          can_see_product_prices: boolean | null;
          whatsapp_group_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type: Database["public"]["Enums"]["company_type"];
          status?: Database["public"]["Enums"]["company_status"];
          default_pickup_time?: string | null;
          transporter_company_id?: string | null;
          can_see_product_prices?: boolean | null;
          whatsapp_group_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: Database["public"]["Enums"]["company_type"];
          status?: Database["public"]["Enums"]["company_status"];
          default_pickup_time?: string | null;
          transporter_company_id?: string | null;
          can_see_product_prices?: boolean | null;
          whatsapp_group_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      product_families: {
        Row: {
          id: string;
          name: string;
          category: string | null;
          // The family photo (migration 0036). Null until a real photo is set.
          image_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          category?: string | null;
          image_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          category?: string | null;
          image_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      product_varieties: {
        Row: {
          id: string;
          family_id: string;
          name: string;
          sizes: string | null;
          pack_type: Database["public"]["Enums"]["pack_type"] | null;
          price: string | null;
          price_range_from: string | null;
          price_range_to: string | null;
          price_type: string | null;
          no_overbooking: string;
          highlight_price_fluctuations: boolean;
          is_seasonal_available: boolean;
          number_of_orders_per_customer: number | null;
          version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          family_id: string;
          name: string;
          sizes?: string | null;
          pack_type?: Database["public"]["Enums"]["pack_type"] | null;
          price?: string | null;
          price_range_from?: string | null;
          price_range_to?: string | null;
          price_type?: string | null;
          no_overbooking?: string;
          highlight_price_fluctuations?: boolean;
          is_seasonal_available?: boolean;
          number_of_orders_per_customer?: number | null;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          family_id?: string;
          name?: string;
          sizes?: string | null;
          pack_type?: Database["public"]["Enums"]["pack_type"] | null;
          price?: string | null;
          price_range_from?: string | null;
          price_range_to?: string | null;
          price_type?: string | null;
          no_overbooking?: string;
          highlight_price_fluctuations?: boolean;
          is_seasonal_available?: boolean;
          number_of_orders_per_customer?: number | null;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "product_varieties_family_id_product_families_id_fk";
            columns: ["family_id"];
            isOneToOne: false;
            referencedRelation: "product_families";
            referencedColumns: ["id"];
          },
        ];
      };
      grower_products: {
        Row: {
          company_id: string;
          product_variety_id: string;
          created_at: string;
        };
        Insert: {
          company_id: string;
          product_variety_id: string;
          created_at?: string;
        };
        Update: {
          company_id?: string;
          product_variety_id?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "grower_products_company_id_companies_id_fk";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "grower_products_product_variety_id_product_varieties_id_fk";
            columns: ["product_variety_id"];
            isOneToOne: false;
            referencedRelation: "product_varieties";
            referencedColumns: ["id"];
          },
        ];
      };
      product_customer_caps: {
        Row: {
          product_variety_id: string;
          customer_company_id: string;
          pallet_cap: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          product_variety_id: string;
          customer_company_id: string;
          pallet_cap: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          product_variety_id?: string;
          customer_company_id?: string;
          pallet_cap?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "product_customer_caps_product_variety_id_product_varieties_id_fk";
            columns: ["product_variety_id"];
            isOneToOne: false;
            referencedRelation: "product_varieties";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "product_customer_caps_customer_company_id_companies_id_fk";
            columns: ["customer_company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
        ];
      };
      profile_blocked_products: {
        Row: {
          created_at: string;
          product_variety_id: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          product_variety_id: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          product_variety_id?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "profile_blocked_products_product_variety_id_product_varieties_i";
            columns: ["product_variety_id"];
            isOneToOne: false;
            referencedRelation: "product_varieties";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "profile_blocked_products_user_id_profiles_user_id_fk";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["user_id"];
          },
        ];
      };
      profiles: {
        Row: {
          company_id: string;
          created_at: string;
          display_name: string;
          must_change_password: boolean;
          phone_number: string | null;
          role: Database["public"]["Enums"]["user_role"];
          updated_at: string;
          user_id: string;
        };
        Insert: {
          company_id: string;
          created_at?: string;
          display_name: string;
          must_change_password?: boolean;
          phone_number?: string | null;
          role: Database["public"]["Enums"]["user_role"];
          updated_at?: string;
          user_id: string;
        };
        Update: {
          company_id?: string;
          created_at?: string;
          display_name?: string;
          must_change_password?: boolean;
          phone_number?: string | null;
          role?: Database["public"]["Enums"]["user_role"];
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_company_id_companies_id_fk";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
        ];
      };
      trading_days: {
        Row: {
          id: string;
          trade_date: string;
          phase: Database["public"]["Enums"]["trading_day_phase"];
          initiated_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          trade_date: string;
          phase?: Database["public"]["Enums"]["trading_day_phase"];
          initiated_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          trade_date?: string;
          phase?: Database["public"]["Enums"]["trading_day_phase"];
          initiated_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "trading_days_initiated_by_profiles_user_id_fk";
            columns: ["initiated_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["user_id"];
          },
        ];
      };
      daily_shops: {
        Row: {
          id: string;
          trading_day_id: string;
          status: Database["public"]["Enums"]["daily_shop_status"];
          can_see_prices: boolean;
          opened_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          trading_day_id: string;
          status?: Database["public"]["Enums"]["daily_shop_status"];
          can_see_prices?: boolean;
          opened_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          trading_day_id?: string;
          status?: Database["public"]["Enums"]["daily_shop_status"];
          can_see_prices?: boolean;
          opened_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "daily_shops_trading_day_id_trading_days_id_fk";
            columns: ["trading_day_id"];
            isOneToOne: true;
            referencedRelation: "trading_days";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "daily_shops_opened_by_profiles_user_id_fk";
            columns: ["opened_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["user_id"];
          },
        ];
      };
      daily_arrangements: {
        Row: {
          id: string;
          trading_day_id: string;
          status: Database["public"]["Enums"]["daily_arrangement_status"];
          created_at: string;
          closed_at: string | null;
        };
        Insert: {
          id?: string;
          trading_day_id: string;
          status?: Database["public"]["Enums"]["daily_arrangement_status"];
          created_at?: string;
          closed_at?: string | null;
        };
        Update: {
          id?: string;
          trading_day_id?: string;
          status?: Database["public"]["Enums"]["daily_arrangement_status"];
          created_at?: string;
          closed_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "daily_arrangements_trading_day_id_trading_days_id_fk";
            columns: ["trading_day_id"];
            isOneToOne: true;
            referencedRelation: "trading_days";
            referencedColumns: ["id"];
          },
        ];
      };
      daily_picks: {
        Row: {
          id: string;
          trading_day_id: string;
          grower_company_id: string;
          status: Database["public"]["Enums"]["daily_pick_status"];
          submitted_at: string | null;
          pickup_time: string | null;
          reminder_sent_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          trading_day_id: string;
          grower_company_id: string;
          status?: Database["public"]["Enums"]["daily_pick_status"];
          submitted_at?: string | null;
          pickup_time?: string | null;
          reminder_sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          trading_day_id?: string;
          grower_company_id?: string;
          status?: Database["public"]["Enums"]["daily_pick_status"];
          submitted_at?: string | null;
          pickup_time?: string | null;
          reminder_sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "daily_picks_trading_day_id_trading_days_id_fk";
            columns: ["trading_day_id"];
            isOneToOne: false;
            referencedRelation: "trading_days";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "daily_picks_grower_company_id_companies_id_fk";
            columns: ["grower_company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
        ];
      };
      daily_pick_products: {
        Row: {
          id: string;
          daily_pick_id: string;
          product_variety_id: string;
          pallets_picked: string;
          comment: string | null;
          leftover_pallets: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          daily_pick_id: string;
          product_variety_id: string;
          pallets_picked?: string;
          comment?: string | null;
          leftover_pallets?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          daily_pick_id?: string;
          product_variety_id?: string;
          pallets_picked?: string;
          comment?: string | null;
          leftover_pallets?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "daily_pick_products_daily_pick_id_daily_picks_id_fk";
            columns: ["daily_pick_id"];
            isOneToOne: false;
            referencedRelation: "daily_picks";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "daily_pick_products_product_variety_id_product_varieties_id_fk";
            columns: ["product_variety_id"];
            isOneToOne: false;
            referencedRelation: "product_varieties";
            referencedColumns: ["id"];
          },
        ];
      };
      daily_orders: {
        Row: {
          id: string;
          trading_day_id: string;
          customer_company_id: string;
          status: Database["public"]["Enums"]["daily_order_status"];
          submitted_at: string | null;
          reminder_sent_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          trading_day_id: string;
          customer_company_id: string;
          status?: Database["public"]["Enums"]["daily_order_status"];
          submitted_at?: string | null;
          reminder_sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          trading_day_id?: string;
          customer_company_id?: string;
          status?: Database["public"]["Enums"]["daily_order_status"];
          submitted_at?: string | null;
          reminder_sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "daily_orders_trading_day_id_trading_days_id_fk";
            columns: ["trading_day_id"];
            isOneToOne: false;
            referencedRelation: "trading_days";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "daily_orders_customer_company_id_companies_id_fk";
            columns: ["customer_company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
        ];
      };
      daily_order_products: {
        Row: {
          id: string;
          daily_order_id: string;
          product_variety_id: string;
          pallets_ordered: string;
          comment: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          daily_order_id: string;
          product_variety_id: string;
          pallets_ordered?: string;
          comment?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          daily_order_id?: string;
          product_variety_id?: string;
          pallets_ordered?: string;
          comment?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "daily_order_products_daily_order_id_daily_orders_id_fk";
            columns: ["daily_order_id"];
            isOneToOne: false;
            referencedRelation: "daily_orders";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "daily_order_products_product_variety_id_product_varieties_id_fk";
            columns: ["product_variety_id"];
            isOneToOne: false;
            referencedRelation: "product_varieties";
            referencedColumns: ["id"];
          },
        ];
      };
      order_submission_logs: {
        Row: {
          id: string;
          daily_order_id: string;
          submitted_by: string;
          snapshot: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          daily_order_id: string;
          submitted_by: string;
          snapshot: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          daily_order_id?: string;
          submitted_by?: string;
          snapshot?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "order_submission_logs_daily_order_id_daily_orders_id_fk";
            columns: ["daily_order_id"];
            isOneToOne: false;
            referencedRelation: "daily_orders";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "order_submission_logs_submitted_by_profiles_user_id_fk";
            columns: ["submitted_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["user_id"];
          },
        ];
      };
      arrangement_records: {
        Row: {
          id: string;
          daily_arrangement_id: string;
          daily_pick_product_id: string;
          daily_order_product_id: string;
          customer_company_id: string;
          quantity_pallets: string;
          price: string | null;
          price_type: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          daily_arrangement_id: string;
          daily_pick_product_id: string;
          daily_order_product_id: string;
          customer_company_id: string;
          quantity_pallets: string;
          price?: string | null;
          price_type?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          daily_arrangement_id?: string;
          daily_pick_product_id?: string;
          daily_order_product_id?: string;
          customer_company_id?: string;
          quantity_pallets?: string;
          price?: string | null;
          price_type?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "arrangement_records_daily_arrangement_id_daily_arrangements_id_fk";
            columns: ["daily_arrangement_id"];
            isOneToOne: false;
            referencedRelation: "daily_arrangements";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "arrangement_records_daily_pick_product_id_daily_pick_products_id_fk";
            columns: ["daily_pick_product_id"];
            isOneToOne: false;
            referencedRelation: "daily_pick_products";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "arrangement_records_daily_order_product_id_daily_order_products_id_fk";
            columns: ["daily_order_product_id"];
            isOneToOne: false;
            referencedRelation: "daily_order_products";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "arrangement_records_customer_company_id_companies_id_fk";
            columns: ["customer_company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
        ];
      };
      notification_outbox: {
        Row: {
          id: string;
          trading_day_id: string;
          recipient_type: Database["public"]["Enums"]["notification_recipient_type"];
          recipient_company_id: string;
          template_key: string;
          payload: Json;
          created_at: string;
          sent_at: string | null;
          attempt_count: number;
          last_error: string | null;
          last_attempted_at: string | null;
          sent_targets: string[];
        };
        Insert: {
          id?: string;
          trading_day_id: string;
          recipient_type: Database["public"]["Enums"]["notification_recipient_type"];
          recipient_company_id: string;
          template_key: string;
          payload: Json;
          created_at?: string;
          sent_at?: string | null;
          attempt_count?: number;
          last_error?: string | null;
          last_attempted_at?: string | null;
          sent_targets?: string[];
        };
        Update: {
          id?: string;
          trading_day_id?: string;
          recipient_type?: Database["public"]["Enums"]["notification_recipient_type"];
          recipient_company_id?: string;
          template_key?: string;
          payload?: Json;
          created_at?: string;
          sent_at?: string | null;
          attempt_count?: number;
          last_error?: string | null;
          last_attempted_at?: string | null;
          sent_targets?: string[];
        };
        Relationships: [
          {
            foreignKeyName: "notification_outbox_trading_day_id_trading_days_id_fk";
            columns: ["trading_day_id"];
            isOneToOne: false;
            referencedRelation: "trading_days";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "notification_outbox_recipient_company_id_companies_id_fk";
            columns: ["recipient_company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
        ];
      };
      alert_types: {
        Row: {
          id: string;
          main_text: string;
          second_line_of_text: string | null;
          send_as_whatsapp_default: boolean;
          send_as_notification_default: boolean;
          app_screen: string;
          url_parameter: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          main_text: string;
          second_line_of_text?: string | null;
          send_as_whatsapp_default?: boolean;
          send_as_notification_default?: boolean;
          app_screen: string;
          url_parameter?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          main_text?: string;
          second_line_of_text?: string | null;
          send_as_whatsapp_default?: boolean;
          send_as_notification_default?: boolean;
          app_screen?: string;
          url_parameter?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      notification_templates: {
        Row: {
          id: string;
          template_key: string;
          channel: Database["public"]["Enums"]["notification_channel"];
          title: string | null;
          content: string;
          link: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          template_key: string;
          channel?: Database["public"]["Enums"]["notification_channel"];
          title?: string | null;
          content: string;
          link?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          template_key?: string;
          channel?: Database["public"]["Enums"]["notification_channel"];
          title?: string | null;
          content?: string;
          link?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      notification_settings: {
        Row: {
          id: boolean;
          whatsapp_enabled: boolean;
          close_arrangement_whatsapp_enabled: boolean;
        };
        Insert: {
          id?: boolean;
          whatsapp_enabled?: boolean;
          close_arrangement_whatsapp_enabled?: boolean;
        };
        Update: {
          id?: boolean;
          whatsapp_enabled?: boolean;
          close_arrangement_whatsapp_enabled?: boolean;
        };
        Relationships: [];
      };
      alerts: {
        Row: {
          id: string;
          intended_for_user_id: string;
          alert_type_id: string;
          read: boolean;
          display_record_id: string | null;
          number_for_display: string | null;
          full_name_for_display: string | null;
          send_as_whatsapp: boolean;
          send_as_notification: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          intended_for_user_id: string;
          alert_type_id: string;
          read?: boolean;
          display_record_id?: string | null;
          number_for_display?: string | null;
          full_name_for_display?: string | null;
          send_as_whatsapp: boolean;
          send_as_notification: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          intended_for_user_id?: string;
          alert_type_id?: string;
          read?: boolean;
          display_record_id?: string | null;
          number_for_display?: string | null;
          full_name_for_display?: string | null;
          send_as_whatsapp?: boolean;
          send_as_notification?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "alerts_intended_for_user_id_profiles_user_id_fk";
            columns: ["intended_for_user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "alerts_alert_type_id_alert_types_id_fk";
            columns: ["alert_type_id"];
            isOneToOne: false;
            referencedRelation: "alert_types";
            referencedColumns: ["id"];
          },
        ];
      };
      lifecycle_sessions: {
        Row: {
          id: string;
          trading_day_id: string;
          session_type: Database["public"]["Enums"]["lifecycle_session_type"];
          performed_by: string;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          trading_day_id: string;
          session_type: Database["public"]["Enums"]["lifecycle_session_type"];
          performed_by: string;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          trading_day_id?: string;
          session_type?: Database["public"]["Enums"]["lifecycle_session_type"];
          performed_by?: string;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "lifecycle_sessions_trading_day_id_trading_days_id_fk";
            columns: ["trading_day_id"];
            isOneToOne: false;
            referencedRelation: "trading_days";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "lifecycle_sessions_performed_by_profiles_user_id_fk";
            columns: ["performed_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["user_id"];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      current_role: {
        Args: never;
        Returns: Database["public"]["Enums"]["user_role"];
      };
      current_company_id: {
        Args: never;
        Returns: string;
      };
      save_grower: {
        Args: {
          p_id: string | null;
          p_name: string;
          p_status: Database["public"]["Enums"]["company_status"];
          p_default_pickup_time: string | null;
          p_whatsapp_group_id: string | null;
          p_product_variety_ids: string[];
          p_transporter_company_id?: string | null;
        };
        Returns: Database["public"]["Tables"]["companies"]["Row"];
      };
      save_customer: {
        Args: {
          p_id: string | null;
          p_name: string;
          p_status: Database["public"]["Enums"]["company_status"];
          p_can_see_product_prices: boolean | null;
          p_whatsapp_group_id: string | null;
        };
        Returns: Database["public"]["Tables"]["companies"]["Row"];
      };
      save_transporter: {
        Args: {
          p_id: string | null;
          p_name: string;
          p_status: Database["public"]["Enums"]["company_status"];
          p_whatsapp_group_id: string | null;
        };
        Returns: Database["public"]["Tables"]["companies"]["Row"];
      };
      save_product: {
        Args: {
          p_id: string | null;
          p_family_id: string;
          p_name: string;
          p_sizes: string | null;
          p_pack_type: Database["public"]["Enums"]["pack_type"] | null;
          p_price: number | null;
          p_price_range_from: number | null;
          p_price_range_to: number | null;
          p_price_type: string | null;
          p_no_overbooking: number;
          p_highlight_price_fluctuations: boolean;
          p_is_seasonal_available: boolean;
          p_expected_version: number | null;
          p_customer_pallet_caps: Json;
        };
        Returns: Database["public"]["Tables"]["product_varieties"]["Row"];
      };
      save_user: {
        Args: {
          p_user_id: string;
          p_display_name: string;
          p_role: Database["public"]["Enums"]["user_role"];
          p_company_id: string;
          p_blocked_product_variety_ids: string[];
        };
        Returns: Database["public"]["Tables"]["profiles"]["Row"];
      };
      initiate_business_day: {
        Args: {
          p_trade_date: string;
        };
        Returns: Database["public"]["Tables"]["trading_days"]["Row"];
      };
      open_shop: {
        Args: {
          p_can_see_prices?: boolean;
        };
        Returns: Database["public"]["Tables"]["daily_shops"]["Row"];
      };
      close_shop: {
        Args: Record<PropertyKey, never>;
        Returns: Database["public"]["Tables"]["lifecycle_sessions"]["Row"];
      };
      close_arrangement: {
        Args: Record<PropertyKey, never>;
        Returns: Database["public"]["Tables"]["lifecycle_sessions"]["Row"];
      };
      // Hand-added ahead of migration 0034 actually running — mirrors the
      // shape `supabase gen types` will produce once it does. Regenerate
      // for real after applying that migration; this is a stand-in so
      // `tsc` has something to check the RPC call against in the meantime.
      update_growers_data: {
        Args: Record<PropertyKey, never>;
        Returns: Database["public"]["Tables"]["daily_picks"]["Row"][];
      };
      submit_pick: {
        Args: {
          p_daily_pick_id: string;
        };
        Returns: Database["public"]["Tables"]["daily_picks"]["Row"];
      };
      // Hand-added ahead of migration 0044 actually running — see the
      // note on update_growers_data above for why.
      revert_pick_to_draft: {
        Args: {
          p_daily_pick_id: string;
        };
        Returns: Database["public"]["Tables"]["daily_picks"]["Row"];
      };
      update_pick_product_pallets: {
        Args: {
          p_daily_pick_product_id: string;
          p_pallets_picked: number;
        };
        Returns: Database["public"]["Tables"]["daily_pick_products"]["Row"];
      };
      bootstrap_grower_pick: {
        Args: {
          p_trading_day_id: string;
          p_grower_company_id: string;
        };
        Returns: Database["public"]["Tables"]["daily_picks"]["Row"];
      };
      close_out_pick_leftovers: {
        Args: {
          p_trading_day_id: string;
        };
        Returns: number;
      };
      update_pick_product_details: {
        Args: {
          p_daily_pick_product_id: string;
          p_comment: string | null;
        };
        Returns: Database["public"]["Tables"]["daily_pick_products"]["Row"];
      };
      // The batched, single-transaction save the pick editor uses (migration
      // 0039). The two per-line functions above remain for genuine one-line
      // edits and are still called elsewhere.
      save_pick_lines: {
        Args: {
          p_daily_pick_id: string;
          p_lines: Json;
        };
        Returns: Database["public"]["Tables"]["daily_pick_products"]["Row"][];
      };
      send_pick_reminder: {
        Args: {
          p_daily_pick_id: string;
        };
        Returns: Database["public"]["Tables"]["daily_picks"]["Row"];
      };
      shop_variety_orderability: {
        Args: {
          p_trading_day_id: string;
        };
        Returns: {
          product_variety_id: string;
          is_orderable: boolean;
        }[];
      };
      get_orderable_catalog_for_customer: {
        Args: {
          p_trading_day_id: string;
          p_customer_company_id?: string | null;
        };
        Returns: {
          family_id: string;
          family_name: string;
          variety_id: string;
          variety_name: string;
          pack_type: Database["public"]["Enums"]["pack_type"] | null;
          price: number | null;
          price_range_from: number | null;
          price_range_to: number | null;
          price_type: string | null;
          is_orderable: boolean;
          pallets_ordered: number;
          comment: string | null;
          image_url: string | null;
          max_orderable_for_customer: number;
        }[];
      };
      // The customer order screen's per-line ceiling (migration 0042):
      // least(the variety's number_of_orders_per_customer, remaining stock
      // excluding p_customer_company_id's own demand), floored at 0. Not
      // meant to be called directly by client code — surfaced through
      // get_orderable_catalog_for_customer above and enforced again inside
      // submit_order.
      max_orderable_for_customer: {
        Args: {
          p_trading_day_id: string;
          p_product_variety_id: string;
          p_customer_company_id: string;
        };
        Returns: number;
      };
      submit_order: {
        Args: {
          p_trading_day_id: string;
          p_lines: Json;
          p_customer_company_id?: string | null;
        };
        Returns: Database["public"]["Tables"]["daily_orders"]["Row"];
      };
      send_order_reminder: {
        Args: {
          p_daily_order_id: string;
        };
        Returns: Database["public"]["Tables"]["daily_orders"]["Row"];
      };
      // The drain job's delivery bookkeeping (migration 0038). Both are
      // security invoker — notification_outbox's own backoffice-only RLS is
      // what authorizes the write.
      record_outbox_target_sent: {
        Args: {
          p_outbox_id: string;
          p_target: string;
          p_complete?: boolean;
        };
        Returns: void;
      };
      record_outbox_attempt: {
        Args: {
          p_outbox_id: string;
          p_error: string;
        };
        Returns: number;
      };
      check_arrangement_allocation: {
        Args: {
          p_daily_pick_product_id: string;
          p_daily_order_product_id: string;
          p_quantity_pallets: number;
          p_excluding_record_id: string | null;
        };
        Returns: void;
      };
      create_arrangement_record: {
        Args: {
          p_daily_pick_product_id: string;
          p_daily_order_product_id: string;
          p_quantity_pallets: number;
          p_price?: number | null;
          p_price_type?: string | null;
        };
        Returns: Database["public"]["Tables"]["arrangement_records"]["Row"];
      };
      update_arrangement_record: {
        Args: {
          p_id: string;
          p_quantity_pallets: number;
          p_price?: number | null;
          p_price_type?: string | null;
        };
        Returns: Database["public"]["Tables"]["arrangement_records"]["Row"];
      };
      delete_arrangement_record: {
        Args: {
          p_id: string;
        };
        Returns: void;
      };
      // The arrangement board's one-press allocation upsert (migration 0040).
      // Creates the customer's order line at zero pallets when they never
      // ordered the variety, so no daily_order_product_id is passed in.
      arrange_to_customer: {
        Args: {
          p_daily_pick_product_id: string;
          p_customer_company_id: string;
          p_quantity_pallets: number;
          p_price?: number | null;
          p_price_type?: string | null;
        };
        Returns: Database["public"]["Tables"]["arrangement_records"]["Row"];
      };
      populate_arrangement_prices: {
        Args: {
          p_trading_day_id: string;
        };
        Returns: number;
      };
      build_notification_outbox: {
        Args: {
          p_trading_day_id: string;
        };
        Returns: number;
      };
      substitute_template_placeholders: {
        Args: {
          p_content: string;
          p_first_name: string | null;
          p_order_details: string | null;
          p_trade_date: string | null;
          p_company_name?: string | null;
          p_product_name?: string | null;
          p_product_overbooking?: string | null;
        };
        Returns: string;
      };
      create_alert: {
        Args: {
          p_intended_for_user_id: string;
          p_alert_type_id: string;
          p_display_record_id?: string | null;
          p_number_for_display?: number | null;
          p_full_name_for_display?: string | null;
          p_send_as_whatsapp?: boolean | null;
          p_send_as_notification?: boolean | null;
        };
        Returns: Database["public"]["Tables"]["alerts"]["Row"];
      };
      build_arrangement_alerts: {
        Args: {
          p_trading_day_id: string;
        };
        Returns: number;
      };
      resolve_outbox_dispatch: {
        Args: {
          p_outbox_id: string;
        };
        Returns: {
          target: string;
          message: string;
        }[];
      };
    };
    Enums: {
      user_role: "backoffice" | "grower" | "customer";
      company_type: "backoffice" | "grower" | "customer" | "transporter";
      company_status: "active" | "inactive";
      pack_type: "pallets" | "crates";
      trading_day_phase: "initiated" | "shop_open" | "shop_closed" | "closed";
      daily_shop_status: "open" | "closed";
      daily_arrangement_status: "open" | "closed";
      daily_pick_status: "draft" | "submitted" | "closed";
      daily_order_status: "open" | "submitted";
      lifecycle_session_type:
        | "close_shop"
        | "end_the_day"
        | "historical_initiate_day"
        | "historical_open_shop"
        | "historical_update";
      notification_recipient_type: "grower" | "customer" | "backoffice" | "transporter";
      notification_channel: "whatsapp";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema["CompositeTypes"] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      user_role: ["backoffice", "grower", "customer"],
      company_type: ["backoffice", "grower", "customer", "transporter"],
      company_status: ["active", "inactive"],
      pack_type: ["pallets", "crates"],
      trading_day_phase: ["initiated", "shop_open", "shop_closed", "closed"],
      daily_shop_status: ["open", "closed"],
      daily_arrangement_status: ["open", "closed"],
      daily_pick_status: ["draft", "submitted", "closed"],
      daily_order_status: ["open", "submitted"],
      lifecycle_session_type: [
        "close_shop",
        "end_the_day",
        "historical_initiate_day",
        "historical_open_shop",
        "historical_update",
      ],
      notification_recipient_type: ["grower", "customer", "backoffice", "transporter"],
    },
  },
} as const;
